# Generated by Django 5.1.4 on 2024-12-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=240)),
                ('time', models.CharField(max_length=20)),
                ('teachername', models.CharField(max_length=120)),
                ('numclassroom', models.IntegerField()),
            ],
        ),
    ]
