# Generated by Django 5.1.4 on 2025-04-07 13:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayWeek',
            fields=[
                ('numofday', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('numclassroom', models.IntegerField(default=0)),
                ('NFC', models.CharField(default='none', max_length=50)),
                ('numpostfix', models.CharField(default='-', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('discipline', models.CharField(default='none', max_length=240)),
                ('teachername', models.CharField(default='none', max_length=120)),
                ('time1', models.TimeField(default=datetime.time(0, 0, 30))),
                ('time2', models.TimeField(default=datetime.time(0, 0, 30))),
                ('numofday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.dayweek')),
                ('foreign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.room')),
            ],
        ),
    ]
