# Generated by Django 5.1.4 on 2025-04-14 20:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('roomNumber', models.IntegerField(default=0)),
                ('NFC', models.CharField(default='none', max_length=50, unique=True)),
                ('numpostfix', models.CharField(blank=True, default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(default='none', max_length=240)),
                ('lecturer', models.CharField(default='none', max_length=120)),
                ('startTime', models.TimeField(default=datetime.time(0, 0, 30))),
                ('endTime', models.TimeField(default=datetime.time(0, 0, 30))),
                ('numofday', models.IntegerField(default=0)),
                ('foreign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.room')),
            ],
        ),
    ]
