# Generated by Django 5.1.4 on 2025-04-14 20:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='endTime',
            field=models.TimeField(default=datetime.time(0, 23, 59)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='numofday',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='startTime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
